/*
 * Deal_iFrame.java
 *
 * Created on March 4, 2009, 3:37 PM
 */

package gui;

import bean.Deal;
import database.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author  student
 */
public class Deal_iFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form Deal_iFrame */
    public Deal_iFrame() {
        super(" New Deal ",false,true,false,true);
        initComponents();
        
    }
    
    public void action(){
        try{
            
            
        Deal deal =new Deal();
        deal.setBroker(broker.getText());
        deal.setBrokerage(Integer.parseInt(brokerage.getText()));
        deal.setCheckno(checkno.getText());
        deal.setDealdate(dealdate.getText());
        deal.setInformation(information.getText());
        deal.setOwneradd(owneradd.getText());
        deal.setOwnername(ownername.getText());
        deal.setPaidvia((String)paid.getSelectedItem());
        deal.setPrice_paid(Integer.parseInt(price.getText()));
        deal.setProp_price(Integer.parseInt(propprice.getText()));
        deal.setPropadd(propaddress.getText());
        deal.setTenantadd(tenantadd.getText());
        deal.setTenantname(tenantname.getText());
        deal.setPtype((String)ptype.getSelectedItem());
        deal.setPurpose((String)purpose.getSelectedItem());
        System.out.println("before");
        if(!deal.getPropadd().equals("")&&!deal.getTenantname().equals("")){
        String sql_query="INSERT INTO Deal( Owner_Name,Owner_Address,Tenant_Name,Tenant_Address,Deal_Date,Broker_Name,Cheque_Number,PricePaid,Brokerage," +
             "Paid_Via,Information,Property_Address,Property_Type,Property_Price,Purpose) Values('"+
                                       deal.getOwnername()+"','"+deal.getOwneradd()+"','"+deal.getTenantname()+"','"+deal.getTenantadd()+"','"+
                                   deal.getDealdate()+"','"+deal.getBroker()+"','"+deal.getCheckno()+"',"+deal.getPrice_paid()+","+deal.getBrokerage()+",'"+
                        deal.getPaidvia()+"','"+deal.getInformation()+"','"+deal.getPropadd()+"','"+deal.getPtype()+"',"+deal.getProp_price()+",'"+deal.getPurpose()+
                        "')";
     System.out.println(sql_query);
     Database db =new Database();
     int i = db.insert(sql_query);
     if(i!=0){
      broker.setText("");
      brokerage.setText("");
      checkno.setText("");
      dealdate.setText("");
      information.setText("");
      owneradd.setText("");
      ownername.setText("");
      paid.setSelectedItem(0);
      price.setText("");
      propprice.setText("");
      propaddress.setText("");
      tenantadd.setText("");
      tenantname.setText("");
      ptype.setSelectedIndex(0);
      purpose.setSelectedIndex(0);
      
     
     JOptionPane.showMessageDialog(this,"Operation successfully completed","Successfull",JOptionPane.INFORMATION_MESSAGE);
     }
     else
     JOptionPane.showMessageDialog(this,"Due to some connection error data could not be entered properly\nPlease contact your service provider"," Error ",JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this,"You must have to provide \nProperty Address \nTenanant Name \nPrice, Property Price and Brokerage field"," Error ",JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this,"You must have to provide \nProperty Address \nTenanant Name \nPrice, Property Price and Brokerage field"," Error ",JOptionPane.ERROR_MESSAGE);
        }
    
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ownername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        owneradd = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tenantname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tenantadd = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        propaddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        purpose = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        information = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        ptype = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dealdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        broker = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paid = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        checkno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        brokerage = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        propprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Century", 1, 17));
        jLabel1.setText("Owner's Name ");

        jLabel2.setFont(new java.awt.Font("Century", 1, 17));
        jLabel2.setText("Owner's Address ");

        ownername.setFont(new java.awt.Font("Century", 0, 16));

        owneradd.setColumns(20);
        owneradd.setFont(new java.awt.Font("Century", 0, 16));
        owneradd.setLineWrap(true);
        owneradd.setRows(5);
        jScrollPane1.setViewportView(owneradd);

        jLabel3.setFont(new java.awt.Font("Century", 1, 17));
        jLabel3.setText("Tenant's Name ");

        jLabel4.setFont(new java.awt.Font("Century", 1, 17));
        jLabel4.setText("Tenant's Address ");

        tenantname.setFont(new java.awt.Font("Century", 0, 16));

        tenantadd.setColumns(20);
        tenantadd.setFont(new java.awt.Font("Century", 0, 16));
        tenantadd.setLineWrap(true);
        tenantadd.setRows(5);
        jScrollPane2.setViewportView(tenantadd);

        jLabel10.setFont(new java.awt.Font("Century", 1, 17));
        jLabel10.setText("Property Address");

        propaddress.setFont(new java.awt.Font("Century", 0, 16));

        jLabel11.setFont(new java.awt.Font("Century", 1, 17));
        jLabel11.setText("Purpose ");

        purpose.setFont(new java.awt.Font("Century", 0, 16));
        purpose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELL", "RENTAL" }));

        jLabel12.setFont(new java.awt.Font("Century", 1, 17));
        jLabel12.setText("Special Information ");

        information.setColumns(20);
        information.setFont(new java.awt.Font("Century", 0, 16));
        information.setLineWrap(true);
        information.setRows(5);
        jScrollPane3.setViewportView(information);

        jLabel15.setFont(new java.awt.Font("Century", 1, 17));
        jLabel15.setText("Propety");

        ptype.setFont(new java.awt.Font("Century", 0, 16));
        ptype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PLOT", "FLAT", "OFFICE", "BUNGALOW" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(purpose, 0, 274, Short.MAX_VALUE)
                    .addComponent(ptype, 0, 274, Short.MAX_VALUE)
                    .addComponent(ownername, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(tenantname, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenantname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Century", 1, 17));
        jLabel5.setText("Deal Date ");

        dealdate.setFont(new java.awt.Font("Century", 0, 16));

        jLabel6.setFont(new java.awt.Font("Century", 1, 17));
        jLabel6.setText("Broker Name ");

        broker.setFont(new java.awt.Font("Century", 0, 16));

        jLabel7.setFont(new java.awt.Font("Century", 1, 17));
        jLabel7.setText("Paid By ");

        paid.setFont(new java.awt.Font("Century", 0, 16));
        paid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Cash" }));

        jLabel8.setFont(new java.awt.Font("Century", 1, 17));
        jLabel8.setText("Chek No.");

        checkno.setFont(new java.awt.Font("Century", 0, 16));

        jLabel9.setFont(new java.awt.Font("Century", 1, 17));
        jLabel9.setText("Brokerage ");

        brokerage.setFont(new java.awt.Font("Century", 0, 16));

        save.setBackground(new java.awt.Color(153, 153, 153));
        save.setFont(new java.awt.Font("Century", 0, 16));
        save.setText(" Save ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(153, 153, 153));
        close.setFont(new java.awt.Font("Century", 0, 16));
        close.setText(" Close ");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century", 1, 17));
        jLabel13.setText("Property Price ");

        propprice.setFont(new java.awt.Font("Century", 0, 16));

        jLabel14.setFont(new java.awt.Font("Century", 1, 17));
        jLabel14.setText("Price Paid");

        price.setFont(new java.awt.Font("Century", 0, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealdate, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(broker, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paid, 0, 117, Short.MAX_VALUE)
                                    .addComponent(propprice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brokerage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dealdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(broker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(checkno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(propprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokerage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(close))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        action();// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField broker;
    private javax.swing.JTextField brokerage;
    private javax.swing.JTextField checkno;
    private javax.swing.JButton close;
    private javax.swing.JTextField dealdate;
    private javax.swing.JTextArea information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea owneradd;
    private javax.swing.JTextField ownername;
    private javax.swing.JComboBox paid;
    private javax.swing.JTextField price;
    private javax.swing.JTextField propaddress;
    private javax.swing.JTextField propprice;
    private javax.swing.JComboBox ptype;
    private javax.swing.JComboBox purpose;
    private javax.swing.JButton save;
    private javax.swing.JTextArea tenantadd;
    private javax.swing.JTextField tenantname;
    // End of variables declaration//GEN-END:variables
    
}
