/*
 * Main.java
 *
 * Created on January 26, 2009, 9:50 AM
 */

package gui;

import database.DataTable;
import database.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author  student
 */
public class Main extends javax.swing.JFrame implements DataTable {
    
    /** Creates new form Main */
    Database dbbb;
    public Main() {
        
         dbbb=new Database();
       forloop: for(int i=0;i<3;i++){
        //String s=JOptionPane.showInputDialog(this,"Please Enter Password : \n","Password",JOptionPane.QUESTION_MESSAGE);
        loginD ld = new loginD(this,true);
        ld.setVisible(true);
        char[] passwordstr = ld.pwd.getPassword();
        String usr = ld.uid.getText();
        String s = new String(passwordstr);
        System.out.println(" pass word :"+s);
        
        if(1==dbbb.login(s,usr))
        {
            initComponents();
            setTitle("   Nishtha   ");
        this.setSize(this.getToolkit().getScreenSize());
        break forloop;
        }
        else 
        {
            if(i==2){
            System.exit(0);
            System.out.println("af");}
            
        }
        }
    }
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        rental = new javax.swing.JMenu();
        rental_plot = new javax.swing.JMenu();
        rental_plot_new = new javax.swing.JMenuItem();
        rental_plot_open = new javax.swing.JMenuItem();
        rental_office = new javax.swing.JMenu();
        rental_office_new = new javax.swing.JMenuItem();
        renal_office_open = new javax.swing.JMenuItem();
        rental_flat = new javax.swing.JMenu();
        rental_flat_new = new javax.swing.JMenuItem();
        rental_flat_open = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        sell1 = new javax.swing.JMenu();
        sell_plot_new1 = new javax.swing.JMenuItem();
        sell_office_new1 = new javax.swing.JMenuItem();
        sell_flat_new1 = new javax.swing.JMenuItem();
        sell_ban_new = new javax.swing.JMenuItem();
        purchase1 = new javax.swing.JMenu();
        purchase_plot_new1 = new javax.swing.JMenuItem();
        purchasel_office_new1 = new javax.swing.JMenuItem();
        puchasel_flat_new1 = new javax.swing.JMenuItem();
        purchase_ban_new = new javax.swing.JMenuItem();
        rental1 = new javax.swing.JMenu();
        rental_plot_new1 = new javax.swing.JMenuItem();
        rental_office_new1 = new javax.swing.JMenuItem();
        rental_flat_new1 = new javax.swing.JMenuItem();
        rental_ban_new = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        search = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        new_customer = new javax.swing.JMenuItem();
        open_customerlist = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        newdeal = new javax.swing.JMenuItem();
        opendeallist = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        changepwd = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                winClose(evt);
            }
        });

        rental.setText(" Rental ");

        rental_plot.setText("  Plot  ");

        rental_plot_new.setText("    New  ");
        rental_plot_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_plot_newMouseClicked(evt);
            }
        });
        rental_plot_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_plot_newActionPerformed(evt);
            }
        });
        rental_plot.add(rental_plot_new);

        rental_plot_open.setText("   Open   ");
        rental_plot_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_plot_openActionPerformed(evt);
            }
        });
        rental_plot.add(rental_plot_open);

        rental.add(rental_plot);

        rental_office.setText("  Office");

        rental_office_new.setText("  New  ");
        rental_office_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_office_newMouseClicked(evt);
            }
        });
        rental_office_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_office_newActionPerformed(evt);
            }
        });
        rental_office.add(rental_office_new);

        renal_office_open.setText("  Open  ");
        renal_office_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renal_office_openMouseClicked(evt);
            }
        });
        renal_office_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renal_office_openActionPerformed(evt);
            }
        });
        rental_office.add(renal_office_open);

        rental.add(rental_office);

        rental_flat.setText("   Flat");

        rental_flat_new.setText("  New  ");
        rental_flat_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_flat_newMouseClicked(evt);
            }
        });
        rental_flat_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_flat_newActionPerformed(evt);
            }
        });
        rental_flat.add(rental_flat_new);

        rental_flat_open.setText("  Open  ");
        rental_flat_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_flat_openMouseClicked(evt);
            }
        });
        rental_flat_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_flat_openActionPerformed(evt);
            }
        });
        rental_flat.add(rental_flat_open);

        rental.add(rental_flat);

        jMenuBar1.add(rental);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 255));

        sell1.setBackground(new java.awt.Color(204, 204, 255));
        sell1.setText("  Sell  ");
        sell1.setFont(new java.awt.Font("Tahoma", 0, 14));

        sell_plot_new1.setBackground(new java.awt.Color(204, 204, 255));
        sell_plot_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        sell_plot_new1.setText("Plot               New Entry  ");
        sell_plot_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_plot_newMouseClicked(evt);
            }
        });
        sell_plot_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_plot_newActionPerformed(evt);
            }
        });
        sell1.add(sell_plot_new1);

        sell_office_new1.setBackground(new java.awt.Color(204, 204, 255));
        sell_office_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        sell_office_new1.setText("Office             New Entry");
        sell_office_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_office_newMouseClicked(evt);
            }
        });
        sell_office_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_office_newActionPerformed(evt);
            }
        });
        sell1.add(sell_office_new1);

        sell_flat_new1.setBackground(new java.awt.Color(204, 204, 255));
        sell_flat_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        sell_flat_new1.setText("Flat                  New Entry");
        sell_flat_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_flat_newMouseClicked(evt);
            }
        });
        sell_flat_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_flat_newActionPerformed(evt);
            }
        });
        sell1.add(sell_flat_new1);

        sell_ban_new.setBackground(new java.awt.Color(204, 204, 255));
        sell_ban_new.setFont(new java.awt.Font("Tahoma", 0, 12));
        sell_ban_new.setText("Bungalow        New Entry ");
        sell_ban_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_ban_newMouseClicked(evt);
            }
        });
        sell_ban_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_ban_newActionPerformed(evt);
            }
        });
        sell1.add(sell_ban_new);

        jMenuBar2.add(sell1);

        purchase1.setBackground(new java.awt.Color(204, 204, 255));
        purchase1.setText(" Purchase ");
        purchase1.setFont(new java.awt.Font("Tahoma", 0, 14));

        purchase_plot_new1.setBackground(new java.awt.Color(204, 204, 255));
        purchase_plot_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        purchase_plot_new1.setText("Plot               New Entry ");
        purchase_plot_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase_plot_newMouseClicked(evt);
            }
        });
        purchase_plot_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_plot_newActionPerformed(evt);
            }
        });
        purchase1.add(purchase_plot_new1);

        purchasel_office_new1.setBackground(new java.awt.Color(204, 204, 255));
        purchasel_office_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        purchasel_office_new1.setText("Office            New Entry");
        purchasel_office_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasel_office_newMouseClicked(evt);
            }
        });
        purchasel_office_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasel_office_newActionPerformed(evt);
            }
        });
        purchase1.add(purchasel_office_new1);

        puchasel_flat_new1.setBackground(new java.awt.Color(204, 204, 255));
        puchasel_flat_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        puchasel_flat_new1.setText("Flat               New Entry ");
        puchasel_flat_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puchasel_flat_newMouseClicked(evt);
            }
        });
        puchasel_flat_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puchasel_flat_newActionPerformed(evt);
            }
        });
        purchase1.add(puchasel_flat_new1);

        purchase_ban_new.setBackground(new java.awt.Color(204, 204, 255));
        purchase_ban_new.setFont(new java.awt.Font("Tahoma", 0, 12));
        purchase_ban_new.setText("Bungalow      New Entry ");
        purchase_ban_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase_ban_newMouseClicked(evt);
            }
        });
        purchase_ban_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_ban_newActionPerformed(evt);
            }
        });
        purchase1.add(purchase_ban_new);

        jMenuBar2.add(purchase1);

        rental1.setBackground(new java.awt.Color(204, 204, 255));
        rental1.setText(" Rental ");
        rental1.setFont(new java.awt.Font("Tahoma", 0, 14));

        rental_plot_new1.setBackground(new java.awt.Color(204, 204, 255));
        rental_plot_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rental_plot_new1.setText("Plot               New Entry ");
        rental_plot_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_plot_newMouseClicked(evt);
            }
        });
        rental_plot_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_plot_newActionPerformed(evt);
            }
        });
        rental1.add(rental_plot_new1);

        rental_office_new1.setBackground(new java.awt.Color(204, 204, 255));
        rental_office_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rental_office_new1.setText("Office             New Entry ");
        rental_office_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_office_newMouseClicked(evt);
            }
        });
        rental_office_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_office_newActionPerformed(evt);
            }
        });
        rental1.add(rental_office_new1);

        rental_flat_new1.setBackground(new java.awt.Color(204, 204, 255));
        rental_flat_new1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rental_flat_new1.setText("Flat               New Entry ");
        rental_flat_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_flat_newMouseClicked(evt);
            }
        });
        rental_flat_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_flat_newActionPerformed(evt);
            }
        });
        rental1.add(rental_flat_new1);

        rental_ban_new.setBackground(new java.awt.Color(204, 204, 255));
        rental_ban_new.setFont(new java.awt.Font("Tahoma", 0, 12));
        rental_ban_new.setText("Bungalow       New Entry ");
        rental_ban_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_ban_newMouseClicked(evt);
            }
        });
        rental_ban_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_ban_newActionPerformed(evt);
            }
        });
        rental1.add(rental_ban_new);

        jMenuBar2.add(rental1);

        jMenu4.setBackground(new java.awt.Color(204, 204, 255));
        jMenu4.setText(" Search ");
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 14));

        search.setBackground(new java.awt.Color(204, 204, 255));
        search.setFont(new java.awt.Font("Tahoma", 0, 12));
        search.setText(" Search ");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jMenu4.add(search);

        jMenuBar2.add(jMenu4);

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("  Customer  ");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 14));

        new_customer.setBackground(new java.awt.Color(204, 204, 255));
        new_customer.setFont(new java.awt.Font("Tahoma", 0, 12));
        new_customer.setText("New Customer Rquirement");
        new_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_customerActionPerformed(evt);
            }
        });
        jMenu1.add(new_customer);

        open_customerlist.setBackground(new java.awt.Color(204, 204, 255));
        open_customerlist.setFont(new java.awt.Font("Tahoma", 0, 12));
        open_customerlist.setText("Open Customer List ");
        open_customerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_customerlistActionPerformed(evt);
            }
        });
        jMenu1.add(open_customerlist);

        jMenuBar2.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 204, 255));
        jMenu2.setText("  Deals  ");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 14));

        newdeal.setBackground(new java.awt.Color(204, 204, 255));
        newdeal.setFont(new java.awt.Font("Tahoma", 0, 12));
        newdeal.setText(" New Deal .....");
        newdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdealActionPerformed(evt);
            }
        });
        jMenu2.add(newdeal);

        opendeallist.setBackground(new java.awt.Color(204, 204, 255));
        opendeallist.setFont(new java.awt.Font("Tahoma", 0, 12));
        opendeallist.setText(" Open Deal List  ");
        opendeallist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opendeallistActionPerformed(evt);
            }
        });
        jMenu2.add(opendeallist);

        jMenuBar2.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(204, 204, 255));
        jMenu3.setText("  Settings  ");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 14));

        changepwd.setBackground(new java.awt.Color(204, 204, 255));
        changepwd.setFont(new java.awt.Font("Tahoma", 0, 12));
        changepwd.setText(" Change Password  ... ");
        changepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwdActionPerformed(evt);
            }
        });
        jMenu3.add(changepwd);

        jMenuItem1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jMenuItem1.setText(" Change Username ....");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void winClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_winClose
        dbbb.close();// TODO add your handling code here:
    }//GEN-LAST:event_winClose

    private void sell_plot_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_plot_newActionPerformed
        // TODO add your handling code here:
         
        Model_Frame md  = new Model_Frame( "Sell Plot Entry",true,true,true,true,SELL_PLOT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_sell_plot_newActionPerformed

    private void sell_plot_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_plot_newMouseClicked
        // TODO add your handling code here:
        Model_Frame md  = new Model_Frame( "Sell Plot Entry",true,true,true,true,SELL_PLOT); 
        jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
         
    }//GEN-LAST:event_sell_plot_newMouseClicked

    private void sell_plot_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_plot_openActionPerformed
        // TODO add your handling code here:
       /* Model_List md  = new Model_List("List",true,true,true,true, SELL_PLOT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);*/
    }//GEN-LAST:event_sell_plot_openActionPerformed

    private void sell_office_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_office_newActionPerformed
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Sell Office",true,true,true,true,SELL_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_sell_office_newActionPerformed

    private void sell_office_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_office_newMouseClicked
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Sell Office",true,true,true,true,SELL_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_sell_office_newMouseClicked

    private void sell_office_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_office_openActionPerformed
        // TODO add your handling code here:
       /* Model_List md  = new Model_List("List",true,true,true,true, SELL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);*/
        
    }//GEN-LAST:event_sell_office_openActionPerformed

    private void sell_office_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_office_openMouseClicked
        // TODO add your handling code here:
        /*Model_List md  = new Model_List("List",true,true,true,true, SELL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);*/
    }//GEN-LAST:event_sell_office_openMouseClicked

    private void sell_flat_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_flat_newActionPerformed
        // TODO add your handling code here:
         PN_Model_iFrame md  = new PN_Model_iFrame( "Sell Flat",true,true,true,true,SELL_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_sell_flat_newActionPerformed

    private void sell_flat_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_flat_newMouseClicked
        // TODO add your handling code here:
         PN_Model_iFrame md  = new PN_Model_iFrame( "Sell Flat",true,true,true,true,SELL_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_sell_flat_newMouseClicked

    private void sell_flat_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_flat_openActionPerformed
        // TODO add your handling code here:
        /*Model_List md  = new Model_List("List",true,true,true,true, SELL_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
    }//GEN-LAST:event_sell_flat_openActionPerformed

    private void sell_flat_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_flat_openMouseClicked
        // TODO add your handling code here:
        /*Model_List md  = new Model_List("List",true,true,true,true, SELL_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
    }//GEN-LAST:event_sell_flat_openMouseClicked

    private void purchase_plot_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase_plot_newMouseClicked
        // TODO add your handling code here:
        Model_Frame md  = new Model_Frame( "Purchase Plot",true,true,true,true,PURCHASE_PLOT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_purchase_plot_newMouseClicked

    private void purchase_plot_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_plot_newActionPerformed
        // TODO add your handling code here:
        Model_Frame md  = new Model_Frame( "Purchase Plot",true,true,true,true,PURCHASE_PLOT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_purchase_plot_newActionPerformed

    private void purchase_plot_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_plot_openActionPerformed
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, PURCHASE_PLOT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_purchase_plot_openActionPerformed

    private void purchasel_office_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasel_office_newMouseClicked
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Purchase Office",true,true,true,true,PURCHASE_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_purchasel_office_newMouseClicked

    private void purchasel_office_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasel_office_newActionPerformed
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Purchase Office",true,true,true,true,PURCHASE_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_purchasel_office_newActionPerformed

    private void sell_office_open1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_office_open1MouseClicked
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, SELL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
        
    }//GEN-LAST:event_sell_office_open1MouseClicked

    private void sell_office_open1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_office_open1ActionPerformed
        // TODO add your handling code here:
        /* Model_List md  = new Model_List("List",true,true,true,true, SELL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
    }//GEN-LAST:event_sell_office_open1ActionPerformed

    private void puchasel_flat_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puchasel_flat_newMouseClicked
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Purchase Flat",true,true,true,true,PURCHASE_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_puchasel_flat_newMouseClicked

    private void puchasel_flat_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puchasel_flat_newActionPerformed
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Purchase Flat",true,true,true,true,PURCHASE_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_puchasel_flat_newActionPerformed

    private void purchasel_flat_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasel_flat_openMouseClicked
        // TODO add your handling code here:
        /* Model_List md  = new Model_List("List",true,true,true,true, PURCHASE_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_purchasel_flat_openMouseClicked

    private void purchasel_flat_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasel_flat_openActionPerformed
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, PURCHASE_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_purchasel_flat_openActionPerformed

    private void rental_plot_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_plot_newMouseClicked
        // TODO add your handling code here:
        Model_Frame md  = new Model_Frame( "Rental Plot",true,true,true,true,RENTAL_PLOT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_plot_newMouseClicked

    private void rental_plot_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_plot_newActionPerformed
        // TODO add your handling code here:
        Model_Frame md  = new Model_Frame( "Rental Plot",true,true,true,true,RENTAL_PLOT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_plot_newActionPerformed

    private void rental_plot_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_plot_openActionPerformed
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, RENTAL_PLOT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_rental_plot_openActionPerformed

    private void rental_office_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_office_newMouseClicked
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Rental Office",true,true,true,true,RENTAL_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_office_newMouseClicked

    private void rental_office_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_office_newActionPerformed
        // TODO add your handling code here:
        O_Model_iFrame md  = new O_Model_iFrame( "Rental Office",true,true,true,true,RENTAL_OFFICE); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_office_newActionPerformed

    private void renal_office_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renal_office_openMouseClicked
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, RENTAL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_renal_office_openMouseClicked

    private void renal_office_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renal_office_openActionPerformed
        // TODO add your handling code here:
        /* Model_List md  = new Model_List("List",true,true,true,true, RENTAL_OFFICE,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_renal_office_openActionPerformed

    private void rental_flat_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_flat_newMouseClicked
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Rental Flat",true,true,true,true,RENTAL_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_flat_newMouseClicked

    private void rental_flat_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_flat_newActionPerformed
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Rental Flat",true,true,true,true,RENTAL_FLAT); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_rental_flat_newActionPerformed

    private void rental_flat_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_flat_openMouseClicked
        // TODO add your handling code here:
        /* Model_List md  = new Model_List("List",true,true,true,true, RENTAL_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_rental_flat_openMouseClicked

    private void rental_flat_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_flat_openActionPerformed
        // TODO add your handling code here:
         /*Model_List md  = new Model_List("List",true,true,true,true, RENTAL_FLAT,"OPEN",jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true); */
}//GEN-LAST:event_rental_flat_openActionPerformed

    private void sell_ban_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_ban_newActionPerformed
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Sell Bungalow",true,true,true,true,SELL_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_sell_ban_newActionPerformed

    private void purchase_ban_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_ban_newActionPerformed
        // TODO add your handling code here:
        PN_Model_iFrame md  = new PN_Model_iFrame( "Purchase Bungalow",true,true,true,true,PURCHASE_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
    }//GEN-LAST:event_purchase_ban_newActionPerformed

    private void rental_ban_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_ban_newActionPerformed
PN_Model_iFrame md  = new PN_Model_iFrame( "Rental Bungalow",true,true,true,true,RENTAL_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rental_ban_newActionPerformed

    private void rental_ban_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_ban_newMouseClicked
PN_Model_iFrame md  = new PN_Model_iFrame( "Rental Bungalow",true,true,true,true,RENTAL_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rental_ban_newMouseClicked

    private void purchase_ban_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase_ban_newMouseClicked
PN_Model_iFrame md  = new PN_Model_iFrame( "Purchase Bungalow",true,true,true,true,PURCHASE_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_purchase_ban_newMouseClicked

    private void sell_ban_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_ban_newMouseClicked
PN_Model_iFrame md  = new PN_Model_iFrame( "Sell Bungalow",true,true,true,true,SELL_BUNGALOW); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_sell_ban_newMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
ModelSearch ms = new ModelSearch(this, true,jDesktopPane1);        // TODO add your handling code here:
ms.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void new_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_customerActionPerformed
        Customer_iFrame cif = new Customer_iFrame();
        jDesktopPane1.add(cif);
        cif.setVisible(true);
        
    }//GEN-LAST:event_new_customerActionPerformed

    private void open_customerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_customerlistActionPerformed
       Customer_List md  = new Customer_List("Customer List",true,true,true,true, jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
                    
                    
    }//GEN-LAST:event_open_customerlistActionPerformed

    private void opendeallistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opendeallistActionPerformed
       Deal_List md  = new Deal_List("Customer List",true,true,true,true, jDesktopPane1); 

                    jDesktopPane1.add( md ); // attach internal frame
                    md.setVisible(true);
}//GEN-LAST:event_opendeallistActionPerformed

    private void newdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdealActionPerformed
       Deal_iFrame cif = new Deal_iFrame();
        jDesktopPane1.add(cif);
        cif.setVisible(true);
}//GEN-LAST:event_newdealActionPerformed

    private void changepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwdActionPerformed
        Password_iSetting pif = new Password_iSetting(this,true);        // TODO add your handling code here:
        //jDesktopPane1.add(pif);
        pif.setVisible(true);
        
    }//GEN-LAST:event_changepwdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        User_iSetting pif = new User_iSetting(this,true);        // TODO add your handling code here:
        //jDesktopPane1.add(pif);
        pif.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
/*    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changepwd;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem new_customer;
    private javax.swing.JMenuItem newdeal;
    private javax.swing.JMenuItem open_customerlist;
    private javax.swing.JMenuItem opendeallist;
    private javax.swing.JMenuItem puchasel_flat_new1;
    private javax.swing.JMenu purchase1;
    private javax.swing.JMenuItem purchase_ban_new;
    private javax.swing.JMenuItem purchase_plot_new1;
    private javax.swing.JMenuItem purchasel_office_new1;
    private javax.swing.JMenuItem renal_office_open;
    private javax.swing.JMenu rental;
    private javax.swing.JMenu rental1;
    private javax.swing.JMenuItem rental_ban_new;
    private javax.swing.JMenu rental_flat;
    private javax.swing.JMenuItem rental_flat_new;
    private javax.swing.JMenuItem rental_flat_new1;
    private javax.swing.JMenuItem rental_flat_open;
    private javax.swing.JMenu rental_office;
    private javax.swing.JMenuItem rental_office_new;
    private javax.swing.JMenuItem rental_office_new1;
    private javax.swing.JMenu rental_plot;
    private javax.swing.JMenuItem rental_plot_new;
    private javax.swing.JMenuItem rental_plot_new1;
    private javax.swing.JMenuItem rental_plot_open;
    private javax.swing.JMenuItem search;
    private javax.swing.JMenu sell1;
    private javax.swing.JMenuItem sell_ban_new;
    private javax.swing.JMenuItem sell_flat_new1;
    private javax.swing.JMenuItem sell_office_new1;
    private javax.swing.JMenuItem sell_plot_new1;
    // End of variables declaration//GEN-END:variables
    
}
