/*
 * Password_iSetting.java
 *
 * Created on March 5, 2009, 10:54 AM
 */

package gui;

import bean.Login;
import database.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author  student
 */
public class Password_iSetting extends javax.swing.JDialog {
    
    /** Creates new form Password_iSetting */
    public Password_iSetting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        curpwd = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        rnewpwd = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century", 1, 17));
        jLabel1.setText("User Name");

        uname.setFont(new java.awt.Font("Century", 0, 16));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century", 1, 17));
        jLabel2.setText("Current Password ");

        jLabel3.setFont(new java.awt.Font("Century", 1, 17));
        jLabel3.setText("New Password ");

        curpwd.setFont(new java.awt.Font("Century", 0, 16));
        curpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curpwdActionPerformed(evt);
            }
        });

        newpass.setFont(new java.awt.Font("Century", 0, 16));
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century", 1, 17));
        jLabel4.setText("New Password (Retype) ");

        rnewpwd.setFont(new java.awt.Font("Century", 0, 16));
        rnewpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnewpwdActionPerformed(evt);
            }
        });

        ok.setBackground(new java.awt.Color(153, 153, 153));
        ok.setFont(new java.awt.Font("Century", 0, 16));
        ok.setText(" OK  ");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(153, 153, 153));
        close.setFont(new java.awt.Font("Century", 0, 16));
        close.setText(" Close ");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText(" Change Password ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ok)
                        .addGap(84, 84, 84)
                        .addComponent(close)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rnewpwd)
                            .addComponent(newpass)
                            .addComponent(curpwd)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel5)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(curpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rnewpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void action(){
    
    Login log = new Login();
                char[] pass1 =newpass.getPassword();
                String pwd = new String(pass1);
                char[] pass2 =rnewpwd.getPassword();
                String rpwd = new String(pass2);
                char[] curpass =curpwd.getPassword();
                String cpwd = new String(curpass);
                Database db = new Database();
                
                if(!pwd.equals("")&&pwd.equals(rpwd)&&(1==db.login(cpwd,uname.getText()))){
                    
                    log.setPassword(pwd);
                    log.setUser(uname.getText());
                    String sql= "Update login set password='"+log.getPassword()+"' where password='"+cpwd+"'";
                    System.out.println(sql);
                    int update= db.update(sql);
                    if(update!=0)
                    {
                        JOptionPane.showMessageDialog(this,"Operation successfully completed","Successfull",JOptionPane.INFORMATION_MESSAGE);
                        setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Due to some connection error data could not be entered properly\nPlease contact your service provider"," Error ",JOptionPane.ERROR_MESSAGE);
                        setVisible(false);
                    }
                    }
                  
                
            else{
                JOptionPane.showMessageDialog(this,"Please Fill all entries correctly"," Error ",JOptionPane.ERROR_MESSAGE);
                curpwd.setText("");
                newpass.setText("");
                rnewpwd.setText("");
            }
    
              
    }
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
         action();         
                
    }//GEN-LAST:event_okActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        action();        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void curpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curpwdActionPerformed
action();        // TODO add your handling code here:
    }//GEN-LAST:event_curpwdActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
action();        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void rnewpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnewpwdActionPerformed
action();        // TODO add your handling code here:
    }//GEN-LAST:event_rnewpwdActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password_iSetting(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JPasswordField curpwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField rnewpwd;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
    
}
